name: 'change name yesss'
on:
    push:
        branches:
            - main
    pull_request_target:
        branches:
            - main
jobs:
    coverage:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Jest coverage report
              uses: ArtiomTr/jest-coverage-report-action@v2.0.6

